[package]
name = "TryharderKid/Ui-SOon"
version = "1.0.0"
license = "MIT"
authors = ["TryharderKid"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "lucasmzreal/fastsignal@10.3.2"
Ripple = "littensy/ripple@0.9.1"
Flipper = "reselim/flipper@2.0.0"
