return {

    Accent = Color3.fromHex("#1B5E20"),
    AcrylicMain = Color3.fromHex("#0A0A0A"),
    AcrylicBorder = Color3.fromHex("#1A2F1A"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#0A0A0A"), Color3.fromHex("#0A0A0A")),
    AcrylicNoise = 1,

    TitleBarLine = Color3.fromHex("#1A2F1A"),

    Tab = Color3.fromHex("#203920"),

    Element = Color3.fromHex("#141414"),
    ElementBorder = Color3.fromHex("#1A2F1A"),
    InElementBorder = Color3.fromHex("#1B5E20"),
    ElementTransparency = 0,

    ToggleSlider = Color3.fromHex("#1B5E20"),
    ToggleToggled = Color3.fromHex("#0A0A0A"),

    SliderRail = Color3.fromHex("#1B5E20"),

    DropdownFrame = Color3.fromHex("#141414"),
    DropdownHolder = Color3.fromHex("#141414"),
    DropdownBorder = Color3.fromHex("#1A2F1A"),
    DropdownOption = Color3.fromHex("#203920"),

    Keybind = Color3.fromHex("#141414"),

    Input = Color3.fromHex("#141414"),
    InputFocused = Color3.fromHex("#141414"),
    InputIndicator = Color3.fromHex("#1A2F1A"),

    Dialog = Color3.fromHex("#141414"),
    DialogHolder = Color3.fromHex("#0A0A0A"),
    DialogHolderLine = Color3.fromHex("#1A2F1A"),
    DialogButton = Color3.fromHex("#141414"),
    DialogButtonBorder = Color3.fromHex("#1A2F1A"),
    DialogBorder = Color3.fromHex("#1A2F1A"),
    DialogInput = Color3.fromHex("#141414"),
    DialogInputLine = Color3.fromHex("#1B5E20"),

    Text = Color3.fromHex("#203920"),
    SubText = Color3.fromHex("#1A2F1A"),
    Hover = Color3.fromHex("#1A2F1A"),
    HoverChange = 0.1

}
